### ISSUE TITLE
VirSorter execution for virome data sets

### ISSUE THREAD

**Issue by hoelzer** [EBI-Metagenomics/emg-virify-pipeline#5]
The background noise estimation of VirSorter might fail when running on a data set that is mostly composed of viruses (for example some mock community or enriched sample). The authors recommend to change a parameter if one checks sequences that are mostly viruses: 

> Did you run with the "--virome" option ? This is needed when providing VirSorter with an input file which is mostly (in your case entirely) viral. The reason is that VirSorter was initially designed for microbial single-cell genomes and metagenomes, i.e. in its default mode, VirSorter will first evaluate the different gene content features (i.e. % of viral genes, % of genes without PFAM affiliation, etc) on the whole dataset, and then look for contigs and or regions that are "more viral than average" (roughly). The "--virome" option bypasses this and forces the use of pre-computed features (based on microbial genomes from RefSeq).

See https://github.com/simroux/VirSorter/issues/50

I will implement this as an optional parameter into the nextflow and then we can also compare the outcome.

**Comment by hoelzer** [comment]
I just tested this and the pipeline should really have a parameter to activate ``--virome`` for virsorter or not. Here are just the numbers of high confidence viral predictions (VirSorter cat 1 and 2) with and without ``--virome`` 

Zheng 2019 data set (3319 phages from NCBI)
VirSorter w/o --virome: 2321 contigs
VirSorter w/ --virome:  3280 contigs

Kleiner 2015 co-assembly
10 contigs (w/o virome param)
13 contigs (w/ virome param)

Neto 2015 co-assembly
24 contigs
31 contigs

Kallies 2019
116 contigs
283 contigs

All of these are virus-enriched environments.

**Comment by mberacochea** [comment]
Added as a parameter of the pipeline.
